spring.application.name=demo
server.port=8081

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/billing1
spring.datasource.username=postgres
spring.datasource.password=peter
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Flyway ---
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true


# --- MyBatis ---
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath*:/mappers/**/*.xml
mybatis.type-aliases-package=com.example.demo.entities

# Debug (optional)
logging.level.org.mybatis=DEBUG
logging.level.org.apache.ibatis=DEBUG

# Devtools (optional)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# JWT (dev only)
app.jwt.secret=a68f0d19-89397272-7f1beeb4-f94c0040-82229d76-aacad8a4-9f0d8e5d-ac23b1d3
app.jwt.issuer=demo-api
app.jwt.expiration-minutes=120
